name: Test skopeo-inspect action
on: 
  push:
    branches: 
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Testing whether skopeo action works
    steps:
      - name: Inspect alpine image
        id: inspect-alpine
        uses: prestevez/skopeo-inspect@main
        with:
          target_image: docker://alpine
      - name: Examine outputs
        run: |
          echo "Inspection: ${{ steps.inspect-alpine.outputs.* }}"
          echo "Inspection: ${{ steps.inspect-alpine.outputs.inspection }}"