name: Test skopeo-inspect action
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Testing whether skopeo action works
    steps:
      - name: Inspect parent image
        id: inspection
        uses: prestevez/skopeo-inspect@beta.0.4
      - name: Test skopeo inspect action
        run: echo ${{ steps.inspection.outputs.inspection }}