name: Test skopeo-inspect action
on: 
  push:
    branches: 
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Testing whether skopeo action works
    steps:
      - name: Inspect default image
        id: inspection
        uses: prestevez/skopeo-inspect@main
        with:
          target-image: docker://alpine
      - name: Test skopeo inspect action
        run: |
          echo ${{ steps.inspection.outputs.inspection }}
          echo ${{ steps.inspection.inputs.target-image }}