name: Test skopeo-inspect action
on: 
  push:
    branches: 
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Testing whether skopeo action works
    steps:
      - name: Inspect alpine image
        id: inspection
        uses: prestevez/skopeo-inspect@main
        with:
          target_image: docker://alpine
      - name: Test skopeo inspect action
        run: |
          echo "Inspected image: ${{ steps.inspection.inputs.target_image }}"
          echo "Inspection: ${{ steps.inspection.outputs.INSPECTION }}"